<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0-preview.4</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <EnablePackageValidation Condition="'$(IsPackable)' == 'true'">true</EnablePackageValidation>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
</Project>
