<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="1.*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0-pre.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
    <PackageReference Include="FluentAssertions" Version="7.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Penghou.Zhinu\Penghou.Zhinu.csproj" />
    <ProjectReference Include="..\..\src\Penghou.Zhinu.Sqlite\Penghou.Zhinu.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Penghou.Zhinu.Testing\Penghou.Zhinu.Testing.csproj" />
    <ProjectReference Include="..\..\src\Penghou.Zhinu.Hosting\Penghou.Zhinu.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
